[project]
name = "coding-solutions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiocache>=0.12.3",
    "fastapi>=0.115.14",
    "pydantic>=2.11.7",
    "ruff>=0.12.1",
]
