trigger:
  branches:
    include:
      - features/????/*

variables:
  - name: branch_env_name
    value: ${{ split(variables['Build.SourceBranch'], '/')[3] }}
  - name: branch_name
    value: ${{ variables['Build.SourceBranchName'] }}
